### ISSUE TITLE
Not working onTap in last flutter - 3.7.1

### ISSUE THREAD

**Issue by Bes79** [crawlinknetworks/dropdown_plus#29]

**Comment by sahand77** [comment]
i have the same issue

**Comment by sharpsaravanan** [comment]
After flutter update
 onTap of dropdownItemFn listtile not working. 
please rectify the problem.

Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.22000.1455], locale en-IN)
    • Flutter version 3.7.0 on channel stable at C:\Users\sharp\Documents\flutter_windows_2.5.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (2 weeks ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

**Comment by bw-flagship** [comment]
I fixed it in a fork, you can use it if you want:

```yaml
  dropdown_plus:
    git:
      url: https://github.com/FlagshipApps/dropdown_plus.git
      ref: fc20896d3bd7cee387bae6b3cb9fbdef9176a4b6
```
